version: "3"
services:
# container_name: postgres_db
# postgres database
  postgres_db:
    hostname: postgres_db
    build: ./database/
    restart: always
    networks:
      - pean-app
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
# container_name: express_server
# express api server
  express_server:
    hostname: express_server
    build: ./server/
    networks:
      - pean-app
    depends_on:
      - postgres_db
# container_name: web_app
# angular web app
  web_app:
    hostname: web_app
    build: ./client/
    ports:
      - "80:80"
    networks:
      - pean-app
networks:
  pean-app:
    driver: bridge
volumes:
  postgres_db-data:
    driver: local